version: "3"

services:
  web:
    container_name: web
    image: ifpb/php:7.3-apache-ssh2
    build: .
    networks:
      - app-network
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/

networks:
  app-network:
    driver: bridge
